import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import { Grid } from "@/components/BackGround/Grid";
import { Navbar } from "@/components/Landing/Navbar";

const bricolage = Bricolage_Grotesque({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bricolage.className} antialiased`}>
        <Navbar /> 
        <div className="relative h-screen w-screen">
          <Grid />
          <div className="absolute inset-0 flex items-center justify-center">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}